stages:
  - build
  - deploy

variables:
  DOTNET_VERSION: "8.0"

build:
  stage: build
  script:
    - echo "Building .NET project"
    - dotnet build FISH/FISH.csproj


deploy:
  stage: deploy
  script:
    - echo "Deploying application"
    - dotnet publish FISH/FISH.csproj -c Release -o ./out